FROM alpine:3.3

LABEL vendor=Gadget Sample \
      com.example.is-beta= \
      com.example.is-production="" \
      com.example.version="0.0.1-beta" \
      com.example.release-date="2016-03-29"

# Define working directory.
WORKDIR /data